### ISSUE TITLE
Google services.json

### ISSUE THREAD

**Issue by Fireballion** [purplecandy/ural#1]
could you attach the .json file or provide a link to download it or to make our own model?

**Comment by Fireballion** [comment]
Hi @purplecandy could you tell us how to make the firebase ml .json or provide a way to download it?

**Comment by purplecandy** [comment]
You just need to create a normal firebase project and add an app then add your app id the project's default is `in.kibibyte.ural`  and download the google-json file and proceed to do the rest like usual. 

If you change specify different app id you will have to change the app ids in the project too.

**Comment by Fireballion** [comment]
Solved! Also @purplecandy, I tried a port to iOS but the app gives the following error on device:
package:filex/src/bloc.dart Failed assertion: line 16 pos 9 'directory.existsSync()': Directory/storage.emulated/0/ does not exist.
