### ISSUE TITLE
[flutter] flutter packages get Running "flutter pub get" in flutter...                          Because no versions of folder_picker match >0.3.0 <0.4.0 and folder_picker 0.3.0 depends on filex ^0.2.2, folder_picker ^0.3.0 requires filex ^0.2.2.  Because filex 0.2.2 depends on open_file ^2.0.3 and no versions of filex match >0.2.2 <0.3.0, filex ^0.2.2 requires open_file ^2.0.3.  Thus, folder_picker ^0.3.0 requires open_file ^2.0.3.  So, because ural depends on both open_file ^3.0.1 and folder_picker ^0.3.0, version solving failed. pub get failed (1; So, because ural depends on both open_file ^3.0.1 and folder_picker ^0.3.0, version solving failed.) exit code 1

### ISSUE THREAD

**Issue by Fireballion** [purplecandy/ural#2]
There is the following issue in pub spec when running flutter pub get
[flutter] flutter packages get
Running "flutter pub get" in flutter...                         
Because no versions of folder_picker match >0.3.0 <0.4.0 and folder_picker 0.3.0 depends on filex ^0.2.2, folder_picker ^0.3.0 requires filex ^0.2.2.

Because filex 0.2.2 depends on open_file ^2.0.3 and no versions of filex match >0.2.2 <0.3.0, filex ^0.2.2 requires open_file ^2.0.3.

Thus, folder_picker ^0.3.0 requires open_file ^2.0.3.

So, because ural depends on both open_file ^3.0.1 and folder_picker ^0.3.0, version solving failed.
pub get failed (1; So, because ural depends on both open_file ^3.0.1 and folder_picker ^0.3.0, version solving failed.)
exit code 1

**Comment by purplecandy** [comment]
I never thought that this project would get any attention so everything I implemented was just hacking stuff together to get a prototype done. I would suggest you to avoid building it atm because it's very messy. I'm working on an update that will take around 1-2 weeks but that way cleaner.

You can try changing the open_file version in pubspec.yaml to `^2.0.3`
